### ISSUE TITLE
Can't build LVGL without including `lv_conf.h`

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#1860]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

When trying to build LVGL wihout `lv_conf.h` it fails because `lv_gpu_nxp_pxp_osa.c` and `lv_gpu_nxp_pxp.c` includes it. I'm building LVGL wihout `lv_conf.h` because I'm working on Kconfig support (configuration on `lv_conf_internal.h`).

**To Reproduce**

Pull [this](https://github.com/C47D/lvgl/tree/esp-idf-aware) branch of my local LVGL repo and try to build it.

**Expected behavior**

LVGL being able to compile without `lv_conf.h` included.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/11037705/96824576-bab05b80-13f4-11eb-86f1-cb56afbe05ce.png)

**Additional context**

I've locally fix it (see 903ea8bd) with the following pattern but I don't know if it's the best way to do it:

``lv_gpu_nxp_pxp.c``:
```c
#if defined __has_include
#  if __has_include("lv_conf.h")
#   include "lv_conf.h"
#  else
#   include "lv_conf_internal.h"
#  endif
#endif
```

or this also works (I think it's much clearer):
```c
#if !defined(LV_CONF_SKIP)
#include "lv_conf.h"
#else
#include "lv_conf_internal.h"
#endif
```

**Comment by kisvegabor** [comment]
Hi,

I've just fixed it. Inside LVGL `lv_conf_internal.h` should be included. 

@C47D I also added [lv_conf_kconfig.h](https://github.com/lvgl/lvgl/commit/c03160abc2ca26805513d2e8c6f4b92e10a6a91a) to handle special Kconfig options.

**Comment by C47D** [comment]
`lv_gpu_nxp_pxp_osa.h` also includes `lv_conf.h`directly, I guess it should be also updated?

**Comment by kisvegabor** [comment]
I've just updated it as well.

**Comment by sharpcall** [comment]
This error is still there. Just did a clone and here:

/lvgl/lvgl/examples/widgets/chart# gcc lv_example_chart_
gcc: error: lv_example_chart_: No such file or directory
gcc: fatal error: no input files
compilation terminated.
root@quotestreamer1:/home/programmer/ibkrstreaming/lvgl/lvgl/examples/widgets/chart# gcc lv_example_chart_
lv_example_chart_1.c   lv_example_chart_2.c   lv_example_chart_4.c   lv_example_chart_6.c
lv_example_chart_1.py  lv_example_chart_3.c   lv_example_chart_5.c
root@quotestreamer1:/home/programmer/ibkrstreaming/lvgl/lvgl/examples/widgets/chart# gcc lv_example_chart_5.c
In file included from ../../../src/misc/lv_log.h:16,
                 from ../../../lvgl.h:25,
                 from lv_example_chart_5.c:1:
../../../src/misc/../lv_conf_internal.h:40:14: fatal error: ../../lv_conf.h: No such file or directory
   40 | #    include "../../lv_conf.h"                 /*Else assume lv_conf.h is next to the lvgl folder*/
      |              ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by embeddedt** [comment]
@sharpcall You need more components besides the LVGL repo; I suggest looking into one of the [PC simulator projects](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html) as an example of how to set things up.

**Comment by silverdragon17** [comment]
Hi,
I'm having this error.

![image](https://user-images.githubusercontent.com/26002638/160771204-c360a51b-3a53-4b4d-93ab-020e588164d6.png)

I've checked the lv_conf_internal.h file and it's as per updated code mentioned above. How do I solve it?

**Comment by kisvegabor** [comment]
Are you using the latest version of LVGL?

**Comment by Sarah-C** [comment]
It's back again.

I've just run the new "factory" build for Lilygo T-QT...

                from C:\Users\sarah\Documents\Arduino\sketches\T-QT\factory\factory.ino:5:
c:\users\sarah\documents\arduino\libraries\lvgl\src\lv_conf_internal.h:41:18: fatal error: ../../lv_conf.h: No such file or directory
         #include "../../lv_conf.h"                /*Else assume lv_conf.h is next to the lvgl folder*/
                  ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by kisvegabor** [comment]
Let's continue in #3514
