### ISSUE TITLE
Arc widget does not draw properly after a full revolution

### ISSUE THREAD

**Issue by weixiongmei** [lvgl/lvgl#2490]
### Describe the bug
The Arc widget some times does not draw properly after a full revolution. Please just look at the Arc example from the link https://docs.lvgl.io/master/examples.html , it happens once every few revolutions in the simulator, but on the actual device, it happens every time after a full revolution.

### To Reproduce
```c
#include "../../lv_examples.h"

#if LV_USE_ARC && LV_BUILD_EXAMPLES

static void set_angle(void * obj, int32_t v)
{
    lv_arc_set_value(obj, v);
}

/**
 * Create an arc which acts as a loader.
 */
void lv_example_arc_2(void)
{
  /*Create an Arc*/
  lv_obj_t * arc = lv_arc_create(lv_scr_act());
  lv_arc_set_rotation(arc, 270);
  lv_arc_set_bg_angles(arc, 0, 360);
  lv_obj_remove_style(arc, NULL, LV_PART_KNOB);   /*Be sure the knob is not displayed*/
  lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);  /*To not allow adjusting by click*/
  lv_obj_center(arc);

  lv_anim_t a;
  lv_anim_init(&a);
  lv_anim_set_var(&a, arc);
  lv_anim_set_exec_cb(&a, set_angle);
  lv_anim_set_time(&a, 1000);
  lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);    /*Just for the demo*/
  lv_anim_set_repeat_delay(&a, 500);
  lv_anim_set_values(&a, 0, 100);
  lv_anim_start(&a);
}
#endif
```

### Expected behavior
Good
![image](https://user-images.githubusercontent.com/15250619/130684360-e5b5b6d8-f6a6-4ef1-9099-ca9d756a9f1a.png)

### Screenshots or video
No Good
![image](https://user-images.githubusercontent.com/15250619/130684322-4d43ee08-98ea-4448-a9fe-d296c9ba7141.png)

**Comment by kisvegabor** [comment]
Thanks for the report. I've just fixed it.

**Comment by weixiongmei** [comment]
> Thanks for the report. I've just fixed it.

The Arc widget without the indicator has been fixed, but the Arc widget with the indicator still having problem, please try the following code

```python
##### startup script #####

#!/opt/bin/lv_micropython -i

import lvgl as lv

import display_driver

##### main script #####

# Create an Arc
arc = lv.arc(lv.scr_act())
arc.set_range(0,100)
arc.set_end_angle(200)
arc.set_size(150, 150)
arc.center()

class ArcLoader():
    def __init__(self):
        self.a = 0
        
    def arc_loader_cb(self,tim,arc):
        # print(tim,arc)
        self.a += 5

        arc.set_value(self.a)

        if self.a > 100:
            self.a = 0
            #tim._del()

# create the loader
arc_loader = ArcLoader()

timer = lv.timer_create_basic()
timer.set_period(33)
timer.set_cb(lambda src: arc_loader.arc_loader_cb(timer,arc))
```

![image](https://user-images.githubusercontent.com/15250619/130870674-8518b59b-f9c7-4958-a98c-4d36aea006bf.png)

**Comment by kisvegabor** [comment]
The same in C works well for me.
```c
  while(true)
  {
    lv_arc_set_value(arc, 0);
    for(int i=0;i<100;i++)
    {
      lv_arc_set_value(arc, i);
      lv_task_handler();
      usleep(100 * 1000);
    }
  }

```
![a](https://user-images.githubusercontent.com/7599318/130952455-c79c756c-76fc-4b75-8f68-25125eff58e7.gif)

Note that the McroPython binding is not updated automatically for every commit of LVGL. 
However you can manually pull the latest lvgl version.

**Comment by weixiongmei** [comment]
That's so strange, i have updated to the newest commit, and i still have issue on my ESP32-S2....

**Comment by kisvegabor** [comment]
Do you still see the issue? If so can you reproduce it in C as well? (not Micropython)

**Comment by weixiongmei** [comment]
Yes, i do still having the same issue even updated to the most recent commits.  And the Micropython simulator is having the exact same issue that i'm having. I deleted the sources, and clone it from git again, doesn't helps. And i tried the exact C code that you posted, it has the same issue too, so really don't know what's going on....
![728123132070214587](https://user-images.githubusercontent.com/15250619/131922471-9a2ace2b-1312-47eb-aeef-357707381f99.jpg)
![734793622983780145](https://user-images.githubusercontent.com/15250619/131922476-f1382e99-8571-4cfe-917b-479443babda0.jpg)

**Comment by kisvegabor** [comment]
I'm looking into it. 
As work around to hide the issue you can call `lv_obj_invalidate(arc)` after setting a new value.

**Comment by weixiongmei** [comment]
Thank you, the work around works.... Hope the issue can be fixed soon...

**Comment by kisvegabor** [comment]
I took me some time to understand what is the real problem but I believe now it work well. If still don't at least know I better know how to approach the issue :slightly_smiling_face:  

Please test it and let me know how it works.

**Comment by weixiongmei** [comment]
Hi @kisvegabor, the issue is fixed now, thank you so much for your works...

**Comment by kisvegabor** [comment]
Great, thank you for the feedback!
